# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, -10, 541, 461))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "\'\'\'        本系統為國立高雄科技大學(第一校區)產品與自動化實驗室與\n"
"        非石實業股份有限公司以科技部產學合作計畫開發\n"
"        著作所有，請勿侵權\n"
"\n"
"        開發者:張嘉宏\n"
"\n"
"        科技部計畫編號:MOST 107-2622-E-992-027-CC3\n"
"\n"
"\n"
"        This Automated Design System is developed by Product \n"
"        Development Automation Lab, National kaoshiung University \n"
"        of Science and Technology and NonStoneCo.Ltd under Industry\n"
"        -University Cooperative Research Project of MOST,Taiwan\n"
"\n"
"        Copyright © 2018 Product Developement Automation Lab,NKUST. \n"
"        All rights reserved.\n"
"\n"
"        Developer: Chia-Hung,Chang\n"
"\n"
"        MOST Project serial:MOST 107-2622-E-992-027-CC3\'\'\'"))
